# Generated by Django 5.0.1 on 2024-01-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0010_auto_20200305_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cust',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='cust',
            name='CustLName',
        ),
    ]
