# Generated by Django 5.0.1 on 2024-01-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0011_remove_cust_address_remove_cust_custlname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='FoodName',
            field=models.CharField(max_length=45),
        ),
    ]
