# Generated by Django 5.0.1 on 2024-02-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0012_alter_food_foodname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust',
            name='CustCont',
            field=models.CharField(max_length=11),
        ),
    ]
